name = "ExampleServer"
uuid = "775d25b6-8935-4359-baa0-0dc908b6ff81"
authors = ["Dmitrii Shevelev"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
